#!/usr/bin/make -f

include ../utils/config.mk
objects += src/utils.o src/segmentation.o src/paging.o src/interrupts.o src/scheduler.o src/user.o tp.o
include ../utils/rules.mk
#-include $(dependencies)
